name: CloudHub 2.0 Emergency Ingress Kill Switch

on:
  workflow_dispatch:

jobs:
  engage-kill-switch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Network Drop Script
        env:
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
          ANYPOINT_ORG_ID: ${{ secrets.ANYPOINT_ORG_ID }}
          ANYPOINT_PRIVATE_SPACE_ID: ${{ secrets.ANYPOINT_PRIVATE_SPACE_ID }}
        run: |
          chmod +x ./scripts/kill_switch.sh
          ./scripts/kill_switch.sh
